languageCode:           "en"
title:                  "Flowbite Admin Dashboard"
baseURL:                "http://localhost:1313"
# baseURL:                "https://flowbite-admin-dashboard.vercel.app/"
enableInlineShortcodes: true
canonifyURLs: true

params:
  homepage: "https://flowbite.com/"
  authors: Themesberg
  social_image_path: images/og-image.png
  pis_base_url: "https://pis.healthwallet.li"

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
    style:              colorful
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

outputs:
  home: ["HTML"]
  section: ["HTML", "JSON"]
  page: ["HTML", "JSON"]

outputFormats:
  JSON:
    mediaType: "application/json"
    isPlainText: true
    notAlternative: true

mediaTypes:
  "application/json":
    suffixes:
      - "json"

security:
  enableInlineShortcodes: true
  funcs:
    getenv: ['^HUGO_', '^OPENAI_', '^CI$']
  http:
    mediaTypes:
      "application/json":
        suffixes: ["json"]
    headers:
      "/**":
        "Access-Control-Allow-Origin": "*"
      "/api/**":
        "Content-Type": "application/json"
